x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"


x-service-defaults: &service-defaults
  stop_grace_period: 1s
  entrypoint:
    - "/project/entrypoint.sh"


services:
  db:
    image: postgres:16.4-bookworm
    restart: always
    env_file:
      - ${DB_ENV}
    volumes:
      - .docker_volumes/postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U the-place"]
      start_period: 10s
    <<: *logging


  public_api:
    build: ./backend/public_api
    restart: always
    volumes:
      - "./backend/public_api:/project"
    env_file:
      - ${PUBLIC_API_ENV}
    ports:
      - ${PUBLIC_API_PORT}:8000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "netcat -z localhost 8000"]
      start_period: 10s
    <<: *service-defaults


  # frontend:
  #   build: ./frontend
  #   ports:
  #     - ${FRONTEND_PORT}:8000
  #   depends_on:
  #     public_api:
  #       condition: service_healthy
  #   <<: *logging
